### ISSUE TITLE
Default image needs source to file (Object in MINDS)

### ISSUE THREAD

**Issue by skoehnen** [HumanBrainProject/SANDS#17]

**Comment by lzehl** [comment]
- default image is now called "image.schema.json" #34 which has the property "definedIn" that links to "fileInstance" -> MINDS/openMINDS
- "defaultImage" is a property of "coordinateSpace" #40 which needs discussion, because currently links directly to "fileInstance", but should maybe link to "image.schema.json"
Further discussions should be handled in those issues. I'll close this one.
